services:
  server:
    extends:
      file: compose.base.yaml
      service: .redash
    command: server --reload
    depends_on:
      - postgres
      - redis
    ports:
      - "${REDASH_PORT:-5001}:5000"
      - "5678:5678"
    environment:
      PYTHONUNBUFFERED: 0
  scheduler:
    extends:
      file: compose.base.yaml
      service: .redash
    command: scheduler
    depends_on:
      - server
  worker:
    extends:
      file: compose.base.yaml
      service: .redash
    command: worker
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  email:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped
